### ISSUE TITLE
Question: Memory Source

### ISSUE THREAD

**Issue by harmon25** [evadne/packmatic#6]
I have a use case that requires adding an entry from memory.
Trying to add a json file that is being generated on the server, but I do not want to write to disk.

Something like this:

```elixir
json_str = %{data: "HI"} |> Jason.encode!()
entries = [
  [source: {:memory,  json_str }  path: "data.json"],
]
```

Would that be possible? Or can it be done with the existing source types?

Love how easy it is to stream the archive to a user with the `Packmatic.Conn.send_chunked` function!

Thanks for the great package!

**Comment by harmon25** [comment]
As a workaround - but may be the only good solution...
I am writing the file to `tmp`, and then including it as a :file entry.

Ideally that could be included in the archive without having to write + read it from tmp...

**Comment by evadne** [comment]
@harmon25 👋

This is where the dynamic source type comes up short. A new change as implemented in https://github.com/evadne/packmatic/pull/4 allows custom source types, which will be released soon. Perhaps this will solve your problem.

> Any module which implements `Packmatic.Source` can be used as a Source.

**Comment by evadne** [comment]
The relevant change has been merged into develop. A new release will come to Hex soon.

Check this out
https://github.com/evadne/packmatic/blob/develop/test/packmatic/integration/custom_source_test.exs

You could implement a module that conforms to `Packmatic.Source` and then use that.
